"""Init Database

Revision ID: 8b9ea71e4948
Revises: 
Create Date: 2018-04-23 13:03:27.611987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9ea71e4948'
down_revision = None
branch_labels = None
depends_on = None

"""
When adding upgrade/downgrade data:
- The create table(s) should be set to variables and set global
    global TABLE
    TABLE = op.create_table('TABLE',
    ...
    )
- Adding Upgrade Data in the data_upgrades function
- Note: for the id column, it is auto generated on insert and is not required here
- For more info: http://alembic.zzzcomputing.com/en/latest/ops.html
    op.bulk_insert(TABLE,
        [
            {'column1': data, 'column2': data, ...}
        ]
    )
"""


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    
    data_upgrades()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    
    data_downgrades()

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass
    
def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
